# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GEclfpeNb8xVVkOIhDMoCC_MVTJIqpMY
"""

class Admin:
    # Initialize_Admin_with_name_and_flight_number
    def __init__(self, name, flight_no):
        self.name = name  # Admin_name
        self.flight_no = flight_no  # Assigned_flight_number

    # Get_admin's_name
    def get_name(self):
        return self.name

    # Get_admin's_assigned_flight_number
    def get_flight_no(self):
        return self.flight_no


class Passenger:
    # Initialize_Passenger_with_name, ticket number, and seat number
    def __init__(self, name, ticket_number, seat_number):
        self.name = name  # Passenger name
        self.ticket_number = ticket_number  # Passenger ticket number
        self.seat_number = seat_number  # Passenger seat number

    # Get_passenger's_name
    def get_name(self):
        return self.name

    # Get_passenger's_ticket_number
    def get_ticket_number(self):
        return self.ticket_number

    # Get_passenger's_seat_number
    def get_seat_number(self):
        return self.seat_number


class Flight:
    # Initialize_Flight_with_flight_details
    def __init__(self, flight_number, departure_airport, destination_airport, departure_date_time, arrival_date_time, gate):
        self.flight_number = flight_number  # Flight number
        self.departure_airport = departure_airport  # Departure airport
        self.destination_airport = destination_airport  # Destination airport
        self.departure_date_time = departure_date_time  # Departure date and time
        self.arrival_date_time = arrival_date_time  # Arrival date and time
        self.gate = gate  # Gate number

    # Get_flight_number
    def get_flight_number(self):
        return self.flight_number

    # Get_departure_airport
    def get_departure_airport(self):
        return self.departure_airport

    # Get_destination_airport
    def get_destination_airport(self):
        return self.destination_airport

    # Get_departure_date_an_time
    def get_departure_date_time(self):
        return self.departure_date_time

    # Get_arrival_date_and_time
    def get_arrival_date_time(self):
        return self.arrival_date_time

    # Get_gate_number
    def get_gate(self):
        return self.gate

    # Set_new_arrival_date_and_time
    def set_arrival_date_time(self, new_arrival_date_time):
        self.arrival_date_time = new_arrival_date_time


class BoardingPass:
    # Initialize_BoardingPass_with_passenger_and_flight_details
    def __init__(self, passenger_name, flight_number, departure_airport, destination_airport, departure_date_time, arrival_date_time, gate, seat_number, electronic_ticket):
        self.passenger_name = passenger_name  # Passenger name
        self.flight_number = flight_number  # Flight number
        self.departure_airport = departure_airport  # Departure airport
        self.destination_airport = destination_airport  # Destination airport
        self.departure_date_time = departure_date_time  # Departure date and time
        self.arrival_date_time = arrival_date_time  # Arrival date and time
        self.gate = gate  # Gate number
        self.seat_number = seat_number  # Seat number
        self.electronic_ticket = electronic_ticket  # Electronic ticket number

    # Get_passenger_name
    def get_passenger_name(self):
        return self.passenger_name

    # Get_flight_number
    def get_flight_number(self):
        return self.flight_number

    # Get_departure_airport
    def get_departure_airport(self):
        return self.departure_airport

    # Get_destination_airport
    def get_destination_airport(self):
        return self.destination_airport

    # Get_departure_date_and_time
    def get_departure_date_time(self):
        return self.departure_date_time

    # Get_arrival_date_and_time
    def get_arrival_date_time(self):
        return self.arrival_date_time

    # Get_gate_number
    def get_gate(self):
        return self.gate

    # Get_seat_number
    def get_seat_number(self):
        return self.seat_number

    # Get_electronic_ticket_number
    def get_electronic_ticket(self):
        return self.electronic_ticket

    # Set_new_arrival_date_and_time
    def set_arrival_date_time(self, new_arrival_date_time):
        self.arrival_date_time = new_arrival_date_time

from datetime import datetime
# Get input from the user for Admin
admin_name = input("Enter Admin Name: ")
admin_flight_no = input("Enter Admin Flight Number: ")

# Create an instance of Admin
admin = Admin(admin_name, admin_flight_no)

# Get input from the user for Passenger
passenger_name = input("Enter Passenger Name: ")
passenger_ticket_number = input("Enter Passenger Ticket Number: ")
passenger_seat_number = input("Enter Passenger Seat Number: ")

# Create an instance of Passenger
passenger = Passenger(passenger_name, passenger_ticket_number, passenger_seat_number)

# Get input from the user for Flight
flight_number = input("Enter Flight Number: ")
departure_airport = input("Enter Departure Airport: ")
destination_airport = input("Enter Destination Airport: ")
departure_date_time_str = input("Enter Departure Date and Time (YYYY-MM-DD HH:MM): ")
departure_date_time = datetime.strptime(departure_date_time_str, "%Y-%m-%d %H:%M")
arrival_date_time_str = input("Enter Arrival Date and Time (YYYY-MM-DD HH:MM): ")
arrival_date_time = datetime.strptime(arrival_date_time_str, "%Y-%m-%d %H:%M")
gate = input("Enter Gate Number: ")

# Create an instance of Flight
flight = Flight(flight_number, departure_airport, destination_airport, departure_date_time, arrival_date_time, gate)

# Get input from the user for Boarding Pass
boarding_pass_passenger_name = input("Enter Passenger Name for Boarding Pass: ")
boarding_pass_flight_number = input("Enter Flight Number for Boarding Pass: ")
boarding_pass_departure_airport = input("Enter Departure Airport for Boarding Pass: ")
boarding_pass_destination_airport = input("Enter Destination Airport for Boarding Pass: ")
boarding_pass_departure_date_time_str = input("Enter Departure Date and Time for Boarding Pass (YYYY-MM-DD HH:MM): ")
boarding_pass_departure_date_time = datetime.strptime(boarding_pass_departure_date_time_str, "%Y-%m-%d %H:%M")
boarding_pass_arrival_date_time_str = input("Enter Arrival Date and Time for Boarding Pass (YYYY-MM-DD HH:MM): ")
boarding_pass_arrival_date_time = datetime.strptime(boarding_pass_arrival_date_time_str, "%Y-%m-%d %H:%M")
boarding_pass_gate = input("Enter Gate Number for Boarding Pass: ")
boarding_pass_seat_number = input("Enter Seat Number for Boarding Pass: ")
boarding_pass_electronic_ticket = input("Enter Electronic Ticket Number for Boarding Pass: ")

def validate_gate_number(gate_number):
    # Check if the gate number starts with "Gate-" and has a length greater than 5
    if gate_number.startswith("Gate-") and len(gate_number) > 5:
        return True
    else:
        return False

# Function to prompt user for gate number input and validate it
def enter_gate_number():
    gate_number = input("Enter the gate number for the boarding pass: ")
    if validate_gate_number(gate_number):
        print("Gate number is valid.")
    else:
        print("Invalid gate number entered.")

# Test the function
enter_gate_number()

# Get input from the user for Departure Date and Time
def get_departure_date_time():
    while True:
        departure_date_time_str = input("Enter Departure Date and Time (YYYY-MM-DD HH:MM): ")
        if not departure_date_time_str:
            print("Error: Departure date and time are required. Please enter a valid date and time.")
        else:
            try:
                departure_date_time = datetime.strptime(departure_date_time_str, "%Y-%m-%d %H:%M")
                return departure_date_time
            except ValueError:
                print("Error: Invalid date/time format. Please enter the date/time in the format YYYY-MM-DD HH:MM.")


# Test the Departure Date and Time validation
departure_date_time = get_departure_date_time()
print("Departure Date and Time:", departure_date_time)